// This file may be edited manually or auto-generated using IfcKit at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2018 BuildingSMART International Ltd.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Xml.Serialization;

using BuildingSmart.IFC.IfcGeometricConstraintResource;
using BuildingSmart.IFC.IfcGeometryResource;
using BuildingSmart.IFC.IfcMeasureResource;
using BuildingSmart.IFC.IfcPresentationAppearanceResource;
using BuildingSmart.IFC.IfcPresentationOrganizationResource;
using BuildingSmart.IFC.IfcProfileResource;

namespace BuildingSmart.IFC.IfcGeometricModelResource
{
	public partial class IfcFixedReferenceSweptAreaSolid : IfcSweptAreaSolid
	{
		[DataMember(Order = 0)] 
		[XmlElement]
		[Description("The curve used to define the sweeping operation. The solid is generated by sweeping the <em>SELF\\IfcSweptAreaSolid.SweptArea</em> along the <em>Directrix</em>.")]
		[Required()]
		public IfcCurve Directrix { get; set; }
	
		[DataMember(Order = 1)] 
		[XmlAttribute]
		[Description("The parameter value on the <em>Directrix</em> at which the sweeping operation commences. <span style=\"color:blue\">If no value is provided the start of the sweeping operation is at the start of the <em>Directrix</em>.</span> ")]
		public IfcParameterValue? StartParam { get; set; }
	
		[DataMember(Order = 2)] 
		[XmlAttribute]
		[Description("The parameter value on the <em>Directrix</em> at which the sweeping operation ends. < style=\"color:blue\">If no value is provided the end of the sweeping operation is at the end of the <em>Directrix</em>.</span>")]
		public IfcParameterValue? EndParam { get; set; }
	
		[DataMember(Order = 3)] 
		[XmlElement]
		[Description("The direction providing the fixed axis1 (x-axis) direction for orienting the swept area during the sweeping operation along the <em>Directrix</em>.")]
		[Required()]
		public IfcDirection FixedReference { get; set; }
	
	
		public IfcFixedReferenceSweptAreaSolid(IfcProfileDef __SweptArea, IfcAxis2Placement3D __Position, IfcCurve __Directrix, IfcParameterValue? __StartParam, IfcParameterValue? __EndParam, IfcDirection __FixedReference)
			: base(__SweptArea, __Position)
		{
			this.Directrix = __Directrix;
			this.StartParam = __StartParam;
			this.EndParam = __EndParam;
			this.FixedReference = __FixedReference;
		}
	
	
	}
	
}
