// This file may be edited manually or auto-generated using IfcKit at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2018 BuildingSMART International Ltd.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Xml.Serialization;

using BuildingSmart.IFC.IfcGeometryResource;
using BuildingSmart.IFC.IfcMeasureResource;
using BuildingSmart.IFC.IfcPresentationAppearanceResource;
using BuildingSmart.IFC.IfcPresentationOrganizationResource;
using BuildingSmart.IFC.IfcProfileResource;

namespace BuildingSmart.IFC.IfcGeometricModelResource
{
	public partial class IfcSurfaceCurveSweptAreaSolid : IfcSweptAreaSolid
	{
		[DataMember(Order = 0)] 
		[Description("The curve used to define the sweeping operation. The solid is generated by sweeping the SELF\\IfcSweptAreaSolid.SweptArea along the Directrix.")]
		[Required()]
		public IfcCurve Directrix { get; set; }
	
		[DataMember(Order = 1)] 
		[XmlAttribute]
		[Description("The parameter value on the Directrix at which the sweeping operation commences.")]
		[Required()]
		public IfcParameterValue StartParam { get; set; }
	
		[DataMember(Order = 2)] 
		[XmlAttribute]
		[Description("The parameter value on the Directrix at which the sweeping operation ends.")]
		[Required()]
		public IfcParameterValue EndParam { get; set; }
	
		[DataMember(Order = 3)] 
		[Description("The surface containing the Directrix.")]
		[Required()]
		public IfcSurface ReferenceSurface { get; set; }
	
	
		public IfcSurfaceCurveSweptAreaSolid(IfcProfileDef __SweptArea, IfcAxis2Placement3D __Position, IfcCurve __Directrix, IfcParameterValue __StartParam, IfcParameterValue __EndParam, IfcSurface __ReferenceSurface)
			: base(__SweptArea, __Position)
		{
			this.Directrix = __Directrix;
			this.StartParam = __StartParam;
			this.EndParam = __EndParam;
			this.ReferenceSurface = __ReferenceSurface;
		}
	
	
	}
	
}
