// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2018 BuildingSMART International Ltd.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Xml.Serialization;

using BuildingSmart.IFC.IfcGeometryResource;
using BuildingSmart.IFC.IfcMeasureResource;
using BuildingSmart.IFC.IfcPresentationAppearanceResource;
using BuildingSmart.IFC.IfcPresentationOrganizationResource;
using BuildingSmart.IFC.IfcProfileResource;

namespace BuildingSmart.IFC.IfcGeometricModelResource
{
	[Guid("ff8dc09b-466f-43a5-9ad7-3a555f6f607f")]
	public partial class IfcSurfaceCurveSweptAreaSolid : IfcSweptAreaSolid
	{
		[DataMember(Order=0)] 
		[Required()]
		IfcCurve _Directrix;
	
		[DataMember(Order=1)] 
		[XmlAttribute]
		[Required()]
		IfcParameterValue _StartParam;
	
		[DataMember(Order=2)] 
		[XmlAttribute]
		[Required()]
		IfcParameterValue _EndParam;
	
		[DataMember(Order=3)] 
		[Required()]
		IfcSurface _ReferenceSurface;
	
	
		public IfcSurfaceCurveSweptAreaSolid()
		{
		}
	
		public IfcSurfaceCurveSweptAreaSolid(IfcProfileDef __SweptArea, IfcAxis2Placement3D __Position, IfcCurve __Directrix, IfcParameterValue __StartParam, IfcParameterValue __EndParam, IfcSurface __ReferenceSurface)
			: base(__SweptArea, __Position)
		{
			this._Directrix = __Directrix;
			this._StartParam = __StartParam;
			this._EndParam = __EndParam;
			this._ReferenceSurface = __ReferenceSurface;
		}
	
		[Description("The curve used to define the sweeping operation. The solid is generated by sweepi" +
	    "ng the SELF\\IfcSweptAreaSolid.SweptArea along the Directrix.")]
		public IfcCurve Directrix { get { return this._Directrix; } set { this._Directrix = value;} }
	
		[Description("The parameter value on the Directrix at which the sweeping operation commences.")]
		public IfcParameterValue StartParam { get { return this._StartParam; } set { this._StartParam = value;} }
	
		[Description("The parameter value on the Directrix at which the sweeping operation ends.")]
		public IfcParameterValue EndParam { get { return this._EndParam; } set { this._EndParam = value;} }
	
		[Description("The surface containing the Directrix.")]
		public IfcSurface ReferenceSurface { get { return this._ReferenceSurface; } set { this._ReferenceSurface = value;} }
	
	
	}
	
}
