// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2018 BuildingSMART International Ltd.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Xml.Serialization;

using BuildingSmart.IFC.IfcGeometryResource;
using BuildingSmart.IFC.IfcMeasureResource;
using BuildingSmart.IFC.IfcPresentationAppearanceResource;
using BuildingSmart.IFC.IfcProfileResource;
using BuildingSmart.IFC.IfcTopologyResource;

namespace BuildingSmart.IFC.IfcGeometricModelResource
{
	[Guid("42fca5dd-e781-41ae-b6cd-728492fe33cf")]
	public partial class IfcExtrudedAreaSolidTapered : IfcExtrudedAreaSolid
	{
		[DataMember(Order=0)] 
		[XmlElement("IfcProfileDef")]
		[Required()]
		IfcProfileDef _EndSweptArea;
	
	
		[Description(@"<EPM-HTML>
	The surface defining the end of the swept area. It is given as a profile definition. The position coordinate system of the <em>EndSwptArea</em> is generated by translating the <em>SELF\IfcSweptAreaSolid.Position</em> along the <em>SELF\IfcExtrudedAreaSolid.ExtrudedDirection</em> by the distance of <em>SELF\IfcExtrudedAreaSolid.Depth</em>.
	</EPM-HTML>")]
		public IfcProfileDef EndSweptArea { get { return this._EndSweptArea; } set { this._EndSweptArea = value;} }
	
	
	}
	
}
