using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("Industry Foundation Classes")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("buildingSMART International Ltd.")]
[assembly: AssemblyProduct("IfcKit")]
[assembly: AssemblyCopyright("Copyright © 2018 buildingSMART International Ltd.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// This project and definitions contained within were generated with IfcDoc,
// and may have been manually updated since.
// For producing derivative content, including documentation and other formats,
// IfcDoc will read the compiled assembly (.dll file) in updating state.
// Therefore, anything added that is not pre-generated by IfcDoc may be lost.
// Adding, updating, or removing data definitions may be done directly within these generated files.
// Any other changes (e.g. custom functions) should be done in separate files using partial classes.

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("CB1818B2-236E-4A6B-97F5-265F73DC1356")]
[assembly: AssemblyTitle("BuildingSmart.IFC4X1")]
[assembly: AssemblyVersion("4.1.0.4")]
[assembly: AssemblyFileVersion("4.1.0.4")]
