// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2018 BuildingSMART International Ltd.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace BuildingSmart.IFC.IfcMeasureResource
{
	[Guid("50bbaf7f-8e36-4203-af6a-f7d8f7961de5")]
	public enum IfcDerivedUnitEnum
	{
		ANGULARVELOCITYUNIT = 1,
	
		COMPOUNDPLANEANGLEUNIT = 2,
	
		DYNAMICVISCOSITYUNIT = 3,
	
		HEATFLUXDENSITYUNIT = 4,
	
		INTEGERCOUNTRATEUNIT = 5,
	
		ISOTHERMALMOISTURECAPACITYUNIT = 6,
	
		KINEMATICVISCOSITYUNIT = 7,
	
		LINEARVELOCITYUNIT = 8,
	
		MASSDENSITYUNIT = 9,
	
		MASSFLOWRATEUNIT = 10,
	
		MOISTUREDIFFUSIVITYUNIT = 11,
	
		MOLECULARWEIGHTUNIT = 12,
	
		SPECIFICHEATCAPACITYUNIT = 13,
	
		THERMALADMITTANCEUNIT = 14,
	
		THERMALCONDUCTANCEUNIT = 15,
	
		THERMALRESISTANCEUNIT = 16,
	
		THERMALTRANSMITTANCEUNIT = 17,
	
		VAPORPERMEABILITYUNIT = 18,
	
		VOLUMETRICFLOWRATEUNIT = 19,
	
		ROTATIONALFREQUENCYUNIT = 20,
	
		TORQUEUNIT = 21,
	
		MOMENTOFINERTIAUNIT = 22,
	
		LINEARMOMENTUNIT = 23,
	
		LINEARFORCEUNIT = 24,
	
		PLANARFORCEUNIT = 25,
	
		MODULUSOFELASTICITYUNIT = 26,
	
		SHEARMODULUSUNIT = 27,
	
		LINEARSTIFFNESSUNIT = 28,
	
		ROTATIONALSTIFFNESSUNIT = 29,
	
		MODULUSOFSUBGRADEREACTIONUNIT = 30,
	
		ACCELERATIONUNIT = 31,
	
		CURVATUREUNIT = 32,
	
		HEATINGVALUEUNIT = 33,
	
		IONCONCENTRATIONUNIT = 34,
	
		LUMINOUSINTENSITYDISTRIBUTIONUNIT = 35,
	
		MASSPERLENGTHUNIT = 36,
	
		MODULUSOFLINEARSUBGRADEREACTIONUNIT = 37,
	
		MODULUSOFROTATIONALSUBGRADEREACTIONUNIT = 38,
	
		PHUNIT = 39,
	
		ROTATIONALMASSUNIT = 40,
	
		SECTIONAREAINTEGRALUNIT = 41,
	
		SECTIONMODULUSUNIT = 42,
	
		SOUNDPOWERUNIT = 43,
	
		SOUNDPRESSUREUNIT = 44,
	
		TEMPERATUREGRADIENTUNIT = 45,
	
		THERMALEXPANSIONCOEFFICIENTUNIT = 46,
	
		WARPINGCONSTANTUNIT = 47,
	
		WARPINGMOMENTUNIT = 48,
	
		USERDEFINED = -1,
	
	}
}
